### ISSUE TITLE
I think I bricked my motherboard

### ISSUE THREAD

**Issue by arisvergas** [ChubbyBunny1/Ender-2-PRO-Klipper-HC32#5]
created folder Factory copied the klipper file blank screen comes as described but klipper file didnt wiped from card, tried clipper from octoprint with klipper plugin with no luck tried to flash again no luck< also tried to go back to the original firmware but blank screen still on any suggestions?

**Comment by StarSpangledWanger** [comment]
How did you  go in the end Ari?

**Comment by arisvergas** [comment]
I manage to go back to the original firmware Ender-2pro-hw2.4.s4xx-sw2.2.41_165.bin but this time I Put the firmware in the folder "user" into the SD card.
But I coudn't live with the sd card print method, So I tried again with klipper this time I put the firmware in to "user" folder and worked ok.
I use [kiauh](https://github.com/dw-0/kiauh) setup for Pi, it was more easy than i thought.
